### ISSUE TITLE
`SyntaxError: Unexpected token {` on 1.5.0 Linux release

### ISSUE THREAD

**Issue by kynan** [dataproofer/Dataproofer#139]
### Summary
System: Linux mint 18 (based on Ubuntu 16.04 LTS)
```
$ uname -a
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
### Steps to reproduce
Download & unpack the 1.5.0 Linux release and launch `Dataproofer`.

### Expected behavior
What was supposed to happen? What happened instead?

### Relevant logs and/or screenshots
```
$ ./Dataproofer
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/fr710/local/Dataproofer-linux-x64/resources/atom.asar/browser/init.js:158:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

### Possible fixes?
I was able to launch the development version from the v1.5.0 tag using node v6.9.1.

**Comment by asitemade4u** [comment]
Same here.
