### ISSUE TITLE
/usr/local/lib/node_modules/dataproofer/index.js:72   for (suite of SUITES) {

### ISSUE THREAD

**Issue by b44p** [dataproofer/Dataproofer#140]
### Summary

Ran dataproofer FOO.csv for the first time

### Steps to reproduce

I installed dataproofer cmdline on my  mac using npm -g install and ran dataproofer FOO.csv for the first time.

### Expected behavior
Not throw the error. Fairly basic csv file.

### Relevant logs and/or screenshots

/usr/local/lib/node_modules/dataproofer/index.js:72
  for (suite of SUITES) {
             ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by b44p** [comment]
So it appears that I have to install the individual suites separately to make this work? I might have missed that in the documentation. It is not super obvious, i could be wrong.

Commandline works splendidly now. 

Closing this. Perhaps the install procedure may need to include the suite installation or update the docs.
