### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by palewire** [dataproofer/Dataproofer#207]
```
node --version
v15.8.0
```

```
npm --version
6.14.11
```

```
npm install dataproofer                                                                                                                                                                     
npm ERR! code ENOVERSIONS                                                                      
npm ERR! No valid versions available for dataproofer-core-suite    
                                                                                               
npm ERR! A complete log of this run can be found in:                                                                                                                                          
npm ERR!     /home/palewire/.npm/_logs/2021-05-01T21_32_19_360Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/palewire/.nvm/versions/node/v15.8.0/bin/node',
1 verbose cli   '/home/palewire/.nvm/versions/node/v15.8.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'dataproofer'
1 verbose cli ]
2 info using npm@6.14.11
3 info using node@v15.8.0
4 verbose npm-session b227e1c6dabefec9
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/dataproofer 335ms
8 http fetch GET 200 https://registry.npmjs.org/dataproofer/-/dataproofer-2.0.0.tgz 72ms
9 silly pacote tag manifest for dataproofer@latest fetched in 433ms
10 timing stage:loadCurrentTree Completed in 473ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule dataproofer@2.0.0 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/chalk 200ms
19 http fetch GET 200 https://registry.npmjs.org/lodash 186ms
20 silly pacote range manifest for lodash@^4.17.20 fetched in 192ms
21 silly resolveWithNewModule lodash@4.17.21 checking installable status
22 http fetch GET 404 https://registry.npmjs.org/dataproofer-geo-suite 204ms
23 http fetch GET 304 https://registry.npmjs.org/commander 211ms (from cache)
24 http fetch GET 200 https://registry.npmjs.org/d3 229ms
25 http fetch GET 200 https://registry.npmjs.org/d3/-/d3-4.13.0.tgz 18ms (from cache)
26 http fetch GET 404 https://registry.npmjs.org/dataproofer-info-suite 259ms
27 http fetch GET 404 https://registry.npmjs.org/dataproofertest-js 263ms
28 http fetch GET 404 https://registry.npmjs.org/dataproofer-stats-suite 268ms
29 silly pacote range manifest for d3@^4.2.7 fetched in 287ms
30 silly resolveWithNewModule d3@4.13.0 checking installable status
31 http fetch GET 200 https://registry.npmjs.org/commander/-/commander-7.2.0.tgz 75ms
32 http fetch GET 200 https://registry.npmjs.org/dataproofer-core-suite 288ms
33 silly fetchPackageMetaData error for dataproofer-core-suite@2.0.0 No valid versions available for dataproofer-core-suite
34 http fetch GET 200 https://registry.npmjs.org/chalk/-/chalk-4.1.1.tgz 92ms
35 http fetch GET 304 https://registry.npmjs.org/optimist 97ms (from cache)
36 silly pacote range manifest for commander@^7.2.0 fetched in 306ms
37 silly resolveWithNewModule commander@7.2.0 checking installable status
38 silly pacote range manifest for chalk@^4.1.0 fetched in 309ms
39 silly resolveWithNewModule chalk@4.1.1 checking installable status
40 silly pacote range manifest for optimist@^0.6.1 fetched in 101ms
41 silly resolveWithNewModule optimist@0.6.1 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/indian-ocean 296ms
43 http fetch GET 304 https://registry.npmjs.org/rw 59ms (from cache)
44 silly pacote range manifest for rw@^1.3.3 fetched in 61ms
45 silly resolveWithNewModule rw@1.3.3 checking installable status
46 http fetch GET 200 https://registry.npmjs.org/xlsx 68ms
47 http fetch GET 404 https://registry.npmjs.org/dataproofer-geo-suite 170ms
48 silly fetchPackageMetaData error for dataproofer-geo-suite@2.0.0 404 Not Found - GET https://registry.npmjs.org/dataproofer-geo-suite - Not found
49 http fetch GET 404 https://registry.npmjs.org/dataproofertest-js 176ms
50 silly fetchPackageMetaData error for dataproofertest-js@2.0.0 404 Not Found - GET https://registry.npmjs.org/dataproofertest-js - Not found
51 http fetch GET 404 https://registry.npmjs.org/dataproofer-info-suite 190ms
52 silly fetchPackageMetaData error for dataproofer-info-suite@2.0.0 404 Not Found - GET https://registry.npmjs.org/dataproofer-info-suite - Not found
53 http fetch GET 200 https://registry.npmjs.org/indian-ocean/-/indian-ocean-4.0.2.tgz 168ms
54 silly pacote range manifest for indian-ocean@^4.0.2 fetched in 475ms
55 silly resolveWithNewModule indian-ocean@4.0.2 checking installable status
56 http fetch GET 404 https://registry.npmjs.org/dataproofer-stats-suite 213ms
57 silly fetchPackageMetaData error for dataproofer-stats-suite@2.0.0 404 Not Found - GET https://registry.npmjs.org/dataproofer-stats-suite - Not found
58 http fetch GET 200 https://registry.npmjs.org/xlsx/-/xlsx-0.16.9.tgz 364ms
59 silly pacote range manifest for xlsx@^0.16.9 fetched in 438ms
60 silly resolveWithNewModule xlsx@0.16.9 checking installable status
61 timing stage:rollbackFailedOptional Completed in 0ms
62 timing stage:runTopLevelLifecycles Completed in 1221ms
63 silly saveTree california-coronavirus-scrapers
63 silly saveTree └─┬ dataproofer@2.0.0
63 silly saveTree   ├── chalk@4.1.1
63 silly saveTree   ├── commander@7.2.0
63 silly saveTree   ├── d3@4.13.0
63 silly saveTree   ├── indian-ocean@4.0.2
63 silly saveTree   ├── lodash@4.17.21
63 silly saveTree   ├── optimist@0.6.1
63 silly saveTree   ├── rw@1.3.3
63 silly saveTree   └── xlsx@0.16.9
64 verbose type version
65 verbose stack dataproofer-core-suite: No valid versions available for dataproofer-core-suite
65 verbose stack     at pickManifest (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:39:11)
65 verbose stack     at /home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:24:14
65 verbose stack     at tryCatcher (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
65 verbose stack     at Promise._settlePromiseFromHandler (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:517:31)
65 verbose stack     at Promise._settlePromise (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:574:18)
65 verbose stack     at Promise._settlePromise0 (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:619:10)
65 verbose stack     at Promise._settlePromises (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:699:18)
65 verbose stack     at _drainQueueStep (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
65 verbose stack     at _drainQueue (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
65 verbose stack     at Async._drainQueues (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
65 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/home/palewire/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
65 verbose stack     at processImmediate (node:internal/timers:463:21)
66 verbose cwd /home/palewire/Code/california-coronavirus-scrapers
67 verbose Linux 5.8.0-50-generic
68 verbose argv "/home/palewire/.nvm/versions/node/v15.8.0/bin/node" "/home/palewire/.nvm/versions/node/v15.8.0/bin/npm" "install" "dataproofer"
69 verbose node v15.8.0
70 verbose npm  v6.14.11
71 error code ENOVERSIONS
72 error No valid versions available for dataproofer-core-suite
73 verbose exit [ 1, true ]
```

**Comment by newsroomdev** [comment]
Hey, @palewire great catch! When you get a minute, could you try running the command one more time `npx dataproofer --help`? I believe the issue was when I migrated all the sub-packages over into one repo, I had not properly informed NPM

**Comment by palewire** [comment]
```
npx dataproofer --help
npx: installed 77 in 5.837s
Usage: dataproofer <file>

A proofreader for your data

Options:
  -V, --version              output the version number
  -o, --out <file>           file to output results. default stdout
  -c, --core                 run tests from the core suite
  -i, --info                 run tests from the info suite
  -s, --stats                run tests from the statistical suite
  -g, --geo                  run tests from the geographic suite
  -t, --tests <list>         comma-separated list to use
  -j, --json                 output JSON of test results
  -J, --json-pretty          output an indented JSON of test results
  -S, --summary              output overall test results, excluding pass/fail results
  -v, --verbose              include descriptions about each column
  -x, --exclude              exclude tests that passed
  -m, --sampleMin <int>      minimum number of rows to sample and test
  -M, --sampleMax <int>      maximum number of rows to sample and test
  -r, --sampleRatio <float>  ratio of rows to sample from total rows (default: 25% of the total rows)
  -h, --help                 display help for command
  Examples:

 $ dataproofer my_data.csv
```

**Comment by ejfox** [comment]
@newsroomdev Was this just a temporary transition error from upgrading that should be fixed for everyone now? Or is this a new and different thing?

**Comment by newsroomdev** [comment]
@ejfox this issue appears to be fixed now. I ran the install on a separate machine that had never seen Dataproofer and @palewire also confirmed it was working. Looking at the NPM registry URLs in the error logs, NPM had cached all our old sub-packages as their non-existent git mirrors. After republishing a minor patch in 2.0.4, those URLS are now all updated to point to the latest versions. I'm inclined to close this issue for now, but I'll keep my eyes peeled and we can reopen as needed
